#!/bin/bash
# written by Robert W. Fuller on 100714


# like basename, but written in bash
bashname() {
    local basename

    if [ $# != 1 ] && [ $# != 2 ]; then
        echo "usage:  ${FUNCNAME} NAME [SUFFIX]"
        return 1
    fi

    basename=${1}

    # remove trailing slashes
    while [ "${basename:(-1)}" = "/" ]; do
        basename=${basename%/}
    done

    # remove all characters before final slash
    basename=${basename##*/}

    # remove suffix if specified
    if [ $# == 2 ]; then

        # do we want shortest or longest match here?
        basename=${basename%%${2}}
    fi

    echo -n ${basename}
}


# example:  dump_file ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/bccr_bcm2_0/run1/thetao_O1e_1850-1859.nc bccr_bcm2_0
#
# $1 is the input file
# $2 is the output file
dump_file() {
    eval ${CMD}
    if [ "${CLOBBER}" = "clobber" ]; then
        CLOBBER=append
    fi
}


# example:  dump_run ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/bccr_bcm2_0/run1
dump_run() {
    local dir run file

    CLOBBER=clobber
    run=$(bashname "${1}")
    pushd .
        mkdir -p "${run}"
        cd "${run}"
        for dir; do
            find "${dir}" -name \*.nc -type f | sort \
                | while read file; do dump_file "${file}" "${MODEL}"; done
        done
    popd
}


# example:  dump_runs ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/bccr_bcm2_0
dump_runs() {
    local dir

    MODEL=$(bashname "${1}")
    find "${1}" -mindepth 1 -maxdepth 1 -type d \
        | while read dir; do dump_run "${dir}"; done
}


# example:  dump_models ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao
dump_models() {
    local dir

    find "${1}" -mindepth 1 -maxdepth 1 -type d \
        | while read dir; do dump_runs "${dir}"; done
}


# example:  dump_scenario 20c3m
dump_scenario() {
    local outdir cmd

    outdir="${1}"
    pushd .
        mkdir -p "${outdir}"
        cd "${outdir}"

        cmd=dump_models\ "${MODEL_DIR}"
        eval ${cmd}
    popd
}


# single quotes keeps bash from interpreting the parameters
CMD='ferret -script ocnheat.jnl "${1}" "${2}" "${CLOBBER}" "1" "-65" "0:100@AVE"'

# thetao is the IPCC variable to dump
MODEL_DIR='~/group/ocean_temp/ftp-esg.ucllnl.org/"${1}"/ocn/mo/thetao'

# examples:
#MODEL=bccr_bcm2_0
#dump_run ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/bccr_bcm2_0/run1

#dump_runs ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/csiro_mk3_0
#dump_models ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao

dump_scenario 20c3m
dump_scenario sresa1b
dump_scenario picntrl
