#!/bin/bash

link_priors() {
    iter=${1}
    script=${2}
    prior=${3}

    ln -s pbs1 "${script}_eval_prior=\"${prior}\";nbatch=${iter}"
    ln -s run_${script}.R "${script}_eval_prior=\"${prior}\";nbatch=${iter}".R
}

link_scripts() {
    iter=${1}
    script=${2}

    link_priors $1 $2 uniform
    link_priors $1 $2 beta
    link_priors $1 $2 normal
}

link_runs() {
    iter=${1}

    link_scripts ${1} pri
    link_scripts ${1} inst
}

link_runs 5e5
link_runs 2e6
link_runs 5e6
