#!/bin/bash
#
# Copyright 2010, 2016 Robert W. Fuller <hydrologiccycle@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ -f ./qrun ] && . ./qrun

submit_scripts() {
    iter=${1}
    script=${2}

    submit_priors $1 $2 u
    submit_priors $1 $2 b
    submit_priors $1 $2 n
}

submit_runs() {
    iter=${1}

    submit_scripts ${1} e
    submit_scripts ${1} i
}

#submit_runs 5e5
#submit_runs 2e6
submit_runs 5e6
submit tony
