cmd  <- paste(commandArgs(), collapse=" ")
expr <- sub(".*==(.*)\\.R.*", "\\1", cmd)
expr <- gsub(':', '"', expr)
expr <- gsub(',', ';', expr)
eval(parse(text=expr))

prior <- switch (p, u={ "uniform" }, b={ "beta" }, n={ "normal" })
source("calib.R")
daisConfigAssim(prior=prior, fast_only=T, wide_prior=F)
daisRunFit()
daisRunAssim(nbatch=n)
daisRunPredict()
save.image(paste("d2", expr, ".RData", sep=""))
