cmd  <- paste(commandArgs(), collapse=" ")
expr <- sub(".*_eval_(.*)\\.R.*", "\\1", cmd)
eval(parse(text=expr))

source("calib.R")
daisConfigAssim(prior=prior, instrumental=T, paleo=T)
daisRunFit()
daisRunAssim(nbatch=nbatch)
daisRunPredict(nbatch=nbatch / 5)
save.image(paste(expr, ".RData", sep=""))
