source("calib.R")
daisConfigAssim(fast_dyn=T, wide_prior=F, instrumental=T, paleo=T, expert=NULL, heaviside=T, gamma_pri=F)
daisRunFit()
daisRunAssim(nbatch=2e6)
daisRunPredict()
save.image("tony.RData")
