source("calib.R")
daisConfigAssim(fast_dyn=T, wide_prior=F, instrumental=T, paleo=T, expert=NULL, gamma_pri=T, heaviside=T)
daisRunFit()
daisRunAssim(nbatch=2e6)
daisRunPredict()
save.image("tony.RData")
