#!/bin/bash
# written by Robert W. Fuller on 100714

bashname() {
    local basename

    if [ $# != 1 ] && [ $# != 2 ]; then
        echo "usage:  ${FUNCNAME} NAME [SUFFIX]"
        return 1
    fi

    basename=${1}

    # remove trailing slashes
    while [ "${basename:(-1)}" = "/" ]; do
        basename=${basename%/}
    done

    # remove all characters before final slash
    basename=${basename##*/}

    # remove suffix if specified
    if [ $# == 2 ]; then

        # do we want shortest or longest match here?
        basename=${basename%%${2}}
    fi

    echo -n ${basename}
}

dump_file() {
    #echo ferret -script ocnheat.jnl "${1}" "${2}" "${CLOBBER}" 
    ferret -script ocnheat.jnl "${1}" "${2}" "${CLOBBER}" 
    if [ "${CLOBBER}" = "clobber" ]; then
        CLOBBER=append
    fi
}

dump_dir() {
    local basedir

    CLOBBER=clobber
    for dir; do
        basedir=$(bashname "${dir}")
        find "${dir}" -name \*.nc -path \*run1\* -type f | sort \
            | while read file; do dump_file "${file}" "${basedir}"; done
    done
}

dump_models() {
    find "${1}" -mindepth 1 -maxdepth 1 -type d \
        | while read dir; do dump_dir "${dir}"; done
}

dump_model_class() {
    mkdir -p "${1}"
    cd "${1}"
    dump_models ~/group/ocean_temp/ftp-esg.ucllnl.org/"${1}"/ocn/mo/thetao
    cd ..
}

#dump_dir "$@"

dump_dir ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/bccr_bcm2_0
#dump_models ~/group/ocean_temp/ftp-esg.ucllnl.org/20c3m/ocn/mo/thetao/

#dump_model_class 20c3m
#dump_model_class sresa1b
#dump_model_class picntrl
