cmd    <- paste(commandArgs(), collapse=" ")
print(cmd)
prior  <-            sub(".*pri_(.*)_.*",       "\\1", cmd)
print(prior)
nbatch <- as.numeric(sub(".*pri_.*_(.*)\\.R.*", "\\1", cmd))
print(nbatch)

source("calib.R")
daisConfigAssim(prior=prior)
daisRunFit()
daisRunAssim(nbatch=nbatch)
daisRunPredict()
save.image(paste(prior, "_", nbatch, ".RData", sep=""))
